<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="App.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Thomoku.Core\Thomoku.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="5.1.0" />
    <PackageReference Include="Fable.Browser.Dom" Version="2.20.0" />
    <PackageReference Include="Feliz" Version="3.3.3" />
  </ItemGroup>

</Project>
